name: Build image 
on:  
  push:
    branches: 
      - main
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v4

      - name: Docker Hub Log IN
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            elsuloda/my_app:${{ github.sha }}
            elsuloda/my_app:latest


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Trigger Infra Repo Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_B_PAT }}
          repository: batyrkulova/terraform
          event-type: trigger-deploy
          client-payload: |
            {
              "image_tag": "${{ github.sha }}"
            }
